version: "2.1"

services:
  localstack:
    container_name: "baggy-aws-mock"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=.local/localstack
    volumes:
      - "${PWD}/.local/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
